import os

env = Environment(
    tools=["gcc", "g++", "gas", 'gnulink', "arduino", "ar"],
    ARDUINO_HOME = R"C:\Program Files (x86)\Arduino",
    AVR_BIN=R"$ARDUINO_HOME/hardware/tools/avr/bin",
    UPLOAD_PORT='COM3'
)

env.ConfigureBoard("uno")
p = "$ARDUINO_HOME/hardware/tools/avr"
env.Replace(
    AR = env.File("$AVR_BIN/avr-ar"),
    AS = env.File("$AVR_BIN/avr-gcc"),
    CC = env.File("$AVR_BIN/avr-gcc"),
    CXX = env.File("$AVR_BIN/avr-g++"),
    OBJCOPY = env.File("$AVR_BIN/avr-objcopy"),
    AVRDUDE = env.File("$AVR_BIN/avrdude"),

    AVRCONFIGFILE = env.File('$ARDUINO_HOME/hardware/tools/avr/etc/avrdude.conf')
)
env.Append(
    CPPFLAGS = '--std=c++0x',
    AVRDUDEFLAGS = '-C$AVRCONFIGFILE'
)

core = env.ArduinoCore()
core_libs = [
    env.ArduinoLibrary("Wire"),
    env.ArduinoLibrary("SD"),
    env.ArduinoLibrary("Servo")
]

our_libs = [
    env.ArduinoLibrary("cpplib", '../libraries/StandardCplusplus'),

    env.ArduinoLibrary("I2CDev", '../libraries/I2CDev'),
    env.ArduinoLibrary("ADXL345", '../libraries/ADXL345'),
    env.ArduinoLibrary("ITG3200", '../libraries/ITG3200'),
    env.ArduinoLibrary("BMP085", '../libraries/BMP085'),
    env.ArduinoLibrary("HMC5883L", '../libraries/HMC5883L'),

    env.ArduinoLibrary("gmtl", '../libraries/gmtl'),

    env.ArduinoLibrary("Sensors", '../libraries/Sensors'),
]


sketch = env.Sketch("data_logger", ["data_logger.cpp"] + our_libs[::-1] + core_libs + [core])
env.Upload(sketch)
